name: Release Version Tag

permissions:
  contents: write
  packages: write
  actions: write

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install commitizen and gh
        run: |
          pip install commitizen
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create release
        run: |
          cz bump --changelog --yes -at
          sed -i "s/appVersion: .*/appVersion: $(git describe --tags --abbrev=0)/" charts/celery-roquefort/Chart.yaml
          git add charts/celery-roquefort/Chart.yaml
          git commit --amend --no-edit
          git push
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Docker build workflow
        run: gh workflow run release-docker.yaml --ref "$(git describe --tags --abbrev=0)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Helm chart release workflow
        run: gh workflow run release-helm-chart.yaml --ref "$(git describe --tags --abbrev=0)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
